---

#- name: Install packages for authentication
#  yum: name=cyrus-sasl-plain-2.1.23-15.el6_6.2.x86_64 state=present

#- name: Create user for authentication
#  shell: saslpasswd2 -c -u {{ postfix_domain }} {{ postfix_user }}

- name: Create relay account
  shell: echo "{{ postfix_relayhost }}:25    {{ postfix_user }}:{{ postfix_passwd }}" >> /etc/postfix/sasl_passwd

- name: Create sasl_passwd.db
  shell: postmap hash:/etc/postfix/sasl_passwd
  notify: 
    - restart saslauthd
    - restart postfix