#Handlers for postfix role
---
  - name: Postfix service restart
    service: 
      name=postfix
      state=restarted
      enabled=true

  - name: Saslauthd service restart
    service:
      name=saslauthd
      state=restarted
      enabled=true